name: mandala_generator
description: Application Flutter qui génère des mandalas aléatoires, propose des styles de couleurs (Pastel, Acrylique, Mat, Flash), et permet d'enregistrer/partager + galerie interne.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.0.2
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
